--
-- Table "CALENDAR_WEEKS"
--
CREATE TABLE "WKSP_THARUN"."CALENDAR_WEEKS" 
   (	"WEEK_ID" NUMBER, 
	"WEEK_NUMBER" NUMBER(2,0) NOT NULL ENABLE, 
	"YEAR_NUMBER" NUMBER(4,0) NOT NULL ENABLE, 
	"WEEK_START_DATE" DATE NOT NULL ENABLE, 
	"WEEK_END_DATE" DATE NOT NULL ENABLE, 
	"WEEK_TYPE" VARCHAR2(20) COLLATE "USING_NLS_COMP" DEFAULT 'normal', 
	"HOLIDAY_NAMES" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"BUSINESS_DAYS" NUMBER DEFAULT 5, 
	"IS_SELECTED" VARCHAR2(1) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"NOTES" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("WEEK_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/