--
-- Table "DOCUSIGN_CONFIG"
--
CREATE TABLE "WKSP_THARUN"."DOCUSIGN_CONFIG" 
   (	"CONFIG_KEY" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CONFIG_VALUE" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"UPDATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("CONFIG_KEY")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/