--
-- Table "EMPLOYEE_DATA"
--
CREATE TABLE "WKSP_THARUN"."EMPLOYEE_DATA" 
   (	"EMP_ID" NUMBER, 
	"EMP_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"DEPARTMENT" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SALARY" NUMBER, 
	"HIRE_DATE" DATE, 
	"IS_ACTIVE" VARCHAR2(1) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	 PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/