--
-- Table "GERMAN_HOLIDAYS_SIMPLE"
--
CREATE TABLE "WKSP_THARUN"."GERMAN_HOLIDAYS_SIMPLE" 
   (	"HOLIDAY_DATE" DATE, 
	"HOLIDAY_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"HOLIDAY_TYPE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"STATE_CODE" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("HOLIDAY_DATE")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/