--
-- Table "MI_DOCUMENTS"
--
CREATE TABLE "WKSP_THARUN"."MI_DOCUMENTS" 
   (	"ID" NUMBER, 
	"FILENAME" VARCHAR2(400) COLLATE "USING_NLS_COMP", 
	"MIMETYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BLOB_CONTENT" BLOB, 
	"DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "MI_DOCUMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/