--
-- Table "MV_CUSTOMERS"
--
CREATE TABLE "WKSP_THARUN"."MV_CUSTOMERS" 
   (	"FIRST_NAME" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"STREET" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"DUMMY" VARCHAR2(1) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"
/