--
-- Table "MV_V_T_CUSTOMERS"
--
CREATE TABLE "WKSP_THARUN"."MV_V_T_CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(20) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"
/