--
-- Table "T_API_KEYS"
--
CREATE TABLE "WKSP_THARUN"."T_API_KEYS" 
   (	"KEY_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"KEY_VALUE" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("KEY_NAME")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/