--
-- Table "T_BACKUP_CONFIG"
--
CREATE TABLE "WKSP_THARUN"."T_BACKUP_CONFIG" 
   (	"APP_ID" NUMBER, 
	"APP_LABEL" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"GITHUB_REPO" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"GITHUB_BRANCH" VARCHAR2(100) COLLATE "USING_NLS_COMP" DEFAULT 'main', 
	"BASE_PATH" VARCHAR2(200) COLLATE "USING_NLS_COMP" DEFAULT 'backups', 
	"IS_ENABLED" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 'Y', 
	 PRIMARY KEY ("APP_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/