--
-- Table "T_BACKUP_LOG"
--
CREATE TABLE "WKSP_THARUN"."T_BACKUP_LOG" 
   (	"LOG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LOG_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"APP_ID" NUMBER, 
	"APP_ALIAS" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"HTTP_STATUS" NUMBER, 
	"MESSAGE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"ERROR_CODE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"RUN_DURATION_S" NUMBER, 
	 PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/