--
-- Table "T_BACKUP_CREDENTIALS"
--
CREATE TABLE "WKSP_THARUN"."T_BACKUP_CREDENTIALS" 
   (	"GITHUB_REPO" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"ENCRYPTED_TOKEN" RAW(512), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("GITHUB_REPO")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/