--
-- Table "T_CUSTOM_DATA_IMPORT"
--
CREATE TABLE "WKSP_THARUN"."T_CUSTOM_DATA_IMPORT" 
   (	"EMPNO" NUMBER(4,0) NOT NULL ENABLE, 
	"ENAME" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"JOB" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0), 
	"CREATED" DATE, 
	"LAST_UPDATED" DATE, 
	 PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_T_CUSTOM_MGR" FOREIGN KEY ("MGR")
	  REFERENCES "WKSP_THARUN"."T_CUSTOM_DATA_IMPORT" ("EMPNO") ENABLE, 
	 CONSTRAINT "FK_T_CUSTOM_DEPT" FOREIGN KEY ("DEPTNO")
	  REFERENCES "WKSP_THARUN"."T_CUSTOM_DEPT" ("DEPTNO") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/