--
-- Table "T_CUSTOM_DEPT"
--
CREATE TABLE "WKSP_THARUN"."T_CUSTOM_DEPT" 
   (	"DEPTNO" NUMBER(2,0) NOT NULL ENABLE, 
	"DNAME" VARCHAR2(14) COLLATE "USING_NLS_COMP", 
	"LOC" VARCHAR2(13) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("DEPTNO")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/