--
-- Table "T_DASHBOARD_ITEM_TYPES"
--
CREATE TABLE "WKSP_THARUN"."T_DASHBOARD_ITEM_TYPES" 
   (	"TYPE_ID" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"TITLE" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"ICON" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DEFAULT_WIDTH" NUMBER NOT NULL ENABLE, 
	"DEFAULT_HEIGHT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "T_DASHBOARD_ITEM_TYPES_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/