--
-- Table "T_DASHBOARD_ITEMS"
--
CREATE TABLE "WKSP_THARUN"."T_DASHBOARD_ITEMS" 
   (	"ITEM_IDENT" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DASHBOARD_IDENT" NUMBER NOT NULL ENABLE, 
	"ITEM_TITLE" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"ITEM_WIDTH" NUMBER NOT NULL ENABLE, 
	"ITEM_HEIGHT" NUMBER NOT NULL ENABLE, 
	"ITEM_ORDER_NUMBER" NUMBER, 
	"TYPE_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ATTRIBUTE_01_C" CLOB COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_01" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_02" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_03" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_04" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_05" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "T_DASHBOARD_ITEMS_PK" PRIMARY KEY ("ITEM_IDENT")
  USING INDEX  ENABLE, 
	 CONSTRAINT "T_DASHBOARD_ITEMS_CON" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "WKSP_THARUN"."T_DASHBOARD_ITEM_TYPES" ("TYPE_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/