--
-- Table "T_DOCUSIGN_ENVELOPES"
--
CREATE TABLE "WKSP_THARUN"."T_DOCUSIGN_ENVELOPES" 
   (	"ENVELOPE_ID" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"DOC_ID" NUMBER, 
	"STATUS" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED" DATE, 
	 PRIMARY KEY ("ENVELOPE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_DOC_ID" FOREIGN KEY ("DOC_ID")
	  REFERENCES "WKSP_THARUN"."T_DOCUSIGN_USERS" ("USER_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/