--
-- Table "T_MS_CARD_STATUS"
--
CREATE TABLE "WKSP_THARUN"."T_MS_CARD_STATUS" 
   (	"BENUTZERID" NUMBER NOT NULL ENABLE, 
	"CARD_NUMBER" NUMBER NOT NULL ENABLE, 
	"SUCHEID" NUMBER NOT NULL ENABLE, 
	"MEILENSTEIN" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ERSTELLDATUM" DATE NOT NULL ENABLE, 
	"LETZTE_AENDERUNG_DATUM" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("BENUTZERID", "CARD_NUMBER", "SUCHEID", "MEILENSTEIN")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/