--
-- Table "T_ORACLE_TEXT_ADDRESSES"
--
CREATE TABLE "WKSP_THARUN"."T_ORACLE_TEXT_ADDRESSES" 
   (	"CUSTOMER_ID" NUMBER, 
	"STREET" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "ADDRESSES_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "WKSP_THARUN"."T_ORACLE_TEXT_CUSTOMERS" ("CUSTOMER_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/