--
-- Table "T_ORACLE_TEXT_CUSTOMERS"
--
CREATE TABLE "WKSP_THARUN"."T_ORACLE_TEXT_CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "ORACLE_TEXT_CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/