--
-- Table "T_VISITOR_COUNT"
--
CREATE TABLE "WKSP_THARUN"."T_VISITOR_COUNT" 
   (	"DAY_OCC" DATE NOT NULL ENABLE, 
	"VISITORS" NUMBER NOT NULL ENABLE, 
	"APP_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "T_VISITOR_COUNT_CON" PRIMARY KEY ("APP_ID", "DAY_OCC")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/