--
-- View "V_CUSTOMERS"
--
CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_THARUN"."V_CUSTOMERS" ("CUSTOMER_ID", "NAME", "ADDRESS", "CITY", "STATE", "ZIPCODE", "EMAIL", "PHONE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT CUSTOMER_ID, NAME, ADDRESS, CITY, STATE, ZIPCODE, EMAIL, PHONE 
FROM T_CUSTOMERS
/