--
-- View "V_ORACLE_TEXT_CUSTOMER_ADDRESSES"
--
CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_THARUN"."V_ORACLE_TEXT_CUSTOMER_ADDRESSES" ("FIRST_NAME", "LAST_NAME", "STREET", "CITY", "STATE", "DUMMY") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 
  c.first_name,
  c.last_name,
  a.street,
  a.city,
  a.state,
  CAST(NULL AS VARCHAR2(1)) AS dummy
FROM
  T_ORACLE_TEXT_CUSTOMERS c
JOIN
  T_ORACLE_TEXT_ADDRESSES a ON c.customer_id = a.customer_id
/