--
-- Trigger "TR_T_CUSTOMERS_AUDIT"
--
CREATE OR REPLACE EDITIONABLE TRIGGER "WKSP_THARUN"."TR_T_CUSTOMERS_AUDIT" 
BEFORE INSERT OR UPDATE ON T_CUSTOMERS 
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_DATE := SYSTIMESTAMP;
        :NEW.CREATED_BY := COALESCE(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
        :NEW.UPDATED_DATE := SYSTIMESTAMP;
        :NEW.UPDATED_BY := COALESCE(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
    ELSIF UPDATING THEN
        :NEW.UPDATED_DATE := SYSTIMESTAMP;
        :NEW.UPDATED_BY := COALESCE(SYS_CONTEXT('USERENV', 'OS_USER'), USER);
        -- Preserve the original creation info
        :NEW.CREATED_DATE := :OLD.CREATED_DATE;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
    END IF;
END;
ALTER TRIGGER "WKSP_THARUN"."TR_T_CUSTOMERS_AUDIT" ENABLE
/