--
-- Trigger "TRG_EISENHOWER_TASKS_UPD"
--
CREATE OR REPLACE EDITIONABLE TRIGGER "WKSP_THARUN"."TRG_EISENHOWER_TASKS_UPD" 
    BEFORE UPDATE ON t_eisenhower_tasks
    FOR EACH ROW
BEGIN
    :NEW.updated_date := SYSDATE;
END;
ALTER TRIGGER "WKSP_THARUN"."TRG_EISENHOWER_TASKS_UPD" ENABLE
/