--
-- Trigger "TRG_T_CUSTOM_DATA_IMPORT"
--
CREATE OR REPLACE EDITIONABLE TRIGGER "WKSP_THARUN"."TRG_T_CUSTOM_DATA_IMPORT" 
    BEFORE INSERT OR UPDATE ON T_CUSTOM_DATA_IMPORT
FOR EACH ROW
BEGIN
   IF :new."CREATED" IS NULL THEN
     :new.created := SYSDATE;
   END IF;
   :new.last_updated := SYSDATE;
END;
ALTER TRIGGER "WKSP_THARUN"."TRG_T_CUSTOM_DATA_IMPORT" ENABLE
/