--
-- Procedure "DEBUG"
--
CREATE OR REPLACE EDITIONABLE PROCEDURE "WKSP_THARUN"."DEBUG" (acomment1 IN varchar2 DEFAULT NULL, acomment2 IN varchar2 DEFAULT NULL) IS
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO t_debug(COMMENT_1, COMMENT_2) VALUES (acomment1, acomment2);
    COMMIT;
END;
/